[main]
shell=/usr/bin/fish
font=DejaVu Sans Mono:size=11
pad=4x4

[colors]
background=222222
foreground=c2c2b0

## Normal / regular colors (8)
regular0=191919
regular1=685742
regular2=5f875f
regular3=b36d43
regular4=78824b
regular5=bb7744
regular6=c9a554
regular7=c2c2b0

## Bright colors (8)
bright0=666666
bright1=685742
bright2=5f875f
bright3=b36d43
bright4=78824b
bright5=bb7744
bright6=c9a554
bright7=c2c2b0

## Selection
selection-foreground=191919
selection-background=78824b
