[main]
shell=/usr/bin/fish
font=DejaVu Sans Mono:size=11
pad=4x4

[colors]
background=1e1e1e
foreground=e5e5e5

## Normal / regular colors (8)
regular0=101010
regular1=ee768a
regular2=8be39a
regular3=cdee6d
regular4=e2a978
regular5=efb37f
regular6=e2a978
regular7=e5e5e5

## Bright colors (8)
bright0=7f7f7f
bright1=ee768a
bright2=8be39a
bright3=cdee6d
bright4=e2a978
bright5=efb37f
bright6=e2a978
bright7=e5e5e5

## Selection
selection-foreground=101010
selection-background=e2a978
