[main]
shell=/usr/bin/fish
font=DejaVu Sans Mono:size=11
pad=4x4

[colors]
background=181d21
foreground=e3e6e8

## Normal / regular colors (8)
regular0=111518
regular1=ec7983
regular2=87e897
regular3=f4e68b
regular4=54bbf8
regular5=d282ed
regular6=54bbf8
regular7=e3e6e8

## Bright colors (8)
bright0=9fa8ad
bright1=f7979f
bright2=a3f5b1
bright3=faefa8
bright4=a1bef7
bright5=e2a1f7
bright6=a1f0f7
bright7=f9fafa

## Selection
selection-foreground=111518
selection-background=62c1f8
