#!/bin/sh
# Launch the user's XDG default web browser.
desk=$(xdg-settings get default-web-browser 2>/dev/null || true)
if [ -n "$desk" ]; then
    exec gtk-launch "$desk" "$@"
fi
exec xdg-open "https://"
