#!/bin/sh
# Lemurs is a systemd service on TTY2; logind's session has no seat (VT 0).
# Use Debian seatd (/usr/sbin/seatd, group video).
export XDG_SESSION_TYPE=wayland
export XDG_SESSION_DESKTOP=sway
export XDG_CURRENT_DESKTOP=sway
export XDG_VTNR="${XDG_VTNR:-2}"
unset DISPLAY WAYLAND_DISPLAY SWAYSOCK I3SOCK
unset XDG_SESSION_ID
export LIBSEAT_BACKEND=seatd
exec /usr/bin/sway
