// zoi SDDM theme — QtQuick only, palette driven by theme.conf (generated by zoi-theme)
import QtQuick 2.15
import QtQuick.Controls 2.15

Rectangle {
    id: root
    color: config.bg

    readonly property string accent: config.accent
    readonly property string surface: config.surface
    readonly property string fg: config.fg
    readonly property string muted: config.muted

    width: screenModel.geometry(screenModel.primary).width
    height: screenModel.geometry(screenModel.primary).height

    // Wallpaper
    Image {
        anchors.fill: parent
        source: config.wallpaper
        fillMode: Image.PreserveAspectCrop
        asynchronous: false
    }

    // Dark scrim so the login card stays readable on any wallpaper
    Rectangle {
        anchors.fill: parent
        color: root.color
        opacity: 0.45
    }

    // Login card
    Rectangle {
        id: card
        width: 340
        height: column.implicitHeight + 48
        anchors.centerIn: parent
        color: root.surface
        opacity: 0.96
        radius: 10

        Column {
            id: column
            anchors.centerIn: parent
            spacing: 14
            width: parent.width - 48

            Text {
                width: parent.width
                horizontalAlignment: Text.AlignHCenter
                text: "zoi"
                color: root.accent
                font.family: "DejaVu Sans"
                font.pixelSize: 28
                font.letterSpacing: 6
            }

            TextField {
                id: userField
                width: parent.width
                text: userModel.lastUser
                color: root.fg
                font.pixelSize: 14
                background: Rectangle {
                    color: "transparent"
                    border.color: root.muted
                    border.width: 1
                    radius: 6
                }
                KeyNavigation.backtab: sessionSelector
                KeyNavigation.tab: passwordField
                Keys.onReturnPressed: passwordField.forceActiveFocus()
            }

            TextField {
                id: passwordField
                width: parent.width
                echoMode: TextInput.Password
                placeholderText: "Password"
                placeholderTextColor: root.muted
                color: root.fg
                font.pixelSize: 14
                background: Rectangle {
                    color: "transparent"
                    border.color: passwordField.activeFocus ? root.accent : root.muted
                    border.width: 1
                    radius: 6
                }
                onAccepted: loginButton.clicked()
                Keys.onReturnPressed: loginButton.clicked()
            }

            Button {
                id: loginButton
                width: parent.width
                text: "Log in"
                contentItem: Text {
                    text: loginButton.text
                    color: root.surface
                    horizontalAlignment: Text.AlignHCenter
                    font.pixelSize: 14
                    font.bold: true
                }
                background: Rectangle {
                    color: loginButton.enabled ? root.accent : root.muted
                    radius: 6
                }
                onClicked: sddm.login(userField.text, passwordField.text, sessionSelector.currentIndex)
            }

            Text {
                id: errorMessage
                width: parent.width
                horizontalAlignment: Text.AlignHCenter
                color: "#fb6060"
                font.pixelSize: 12
                text: ""
            }

            ComboBox {
                id: sessionSelector
                width: parent.width
                model: sessionModel
                textRole: "name"
                currentIndex: sessionModel.lastIndex
                font.pixelSize: 12
                background: Rectangle {
                    color: "transparent"
                    border.color: root.muted
                    border.width: 1
                    radius: 6
                }
                KeyNavigation.tab: userField
            }
        }
    }

    Component.onCompleted: {
        if (userField.text === "")
            userField.forceActiveFocus()
        else
            passwordField.forceActiveFocus()
    }

    Connections {
        target: sddm
        function onLoginFailed() {
            errorMessage.text = "Login failed"
            passwordField.selectAll()
            passwordField.forceActiveFocus()
        }
    }

    // Clock, bottom left
    Text {
        anchors.left: parent.left
        anchors.bottom: parent.bottom
        anchors.margins: 24
        color: root.fg
        opacity: 0.7
        font.pixelSize: 14
        text: Qt.formatDateTime(new Date(), "dddd d MMMM, HH:mm")
        Timer {
            interval: 30000
            running: true
            repeat: true
            onTriggered: parent.text = Qt.formatDateTime(new Date(), "dddd d MMMM, HH:mm")
        }
    }
}
