# Generated by ZOI Theme Manager
"ui.background" = { bg = "{{ background }}" }
"ui.background.separator" = { fg = "{{ muted }}" }
"ui.cursor" = { fg = "{{ dark_background }}", bg = "{{ accent }}" }
"ui.cursor.match" = { fg = "{{ dark_background }}", bg = "{{ orange }}" }
"ui.cursor.primary" = { fg = "{{ dark_background }}", bg = "{{ accent }}" }
"ui.selection" = { bg = "{{ selection }}" }
"ui.selection.primary" = { bg = "{{ selection }}" }
"ui.statusline" = { fg = "{{ foreground }}", bg = "{{ dark_background }}" }
"ui.statusline.inactive" = { fg = "{{ muted }}", bg = "{{ darker_background }}" }
"ui.text" = { fg = "{{ foreground }}" }
"ui.text.focus" = { fg = "{{ foreground }}", bg = "{{ lighter_background }}" }
"ui.text.inactive" = { fg = "{{ muted }}" }
"ui.virtual.ruler" = { bg = "{{ lighter_background }}" }
"ui.virtual.indent-guide" = { fg = "{{ muted }}" }
"ui.window" = { bg = "{{ darker_background }}", fg = "{{ muted }}" }
"ui.help" = { bg = "{{ dark_background }}", fg = "{{ foreground }}" }
"ui.popup" = { bg = "{{ lighter_background }}", fg = "{{ foreground }}" }
"ui.menu" = { bg = "{{ lighter_background }}", fg = "{{ foreground }}" }
"ui.menu.selected" = { bg = "{{ accent }}", fg = "{{ dark_background }}" }

"comment" = { fg = "{{ muted }}", modifiers = ["italic"] }
"constant" = { fg = "{{ orange }}" }
"constant.numeric" = { fg = "{{ orange }}" }
"constant.character.escape" = { fg = "{{ red }}" }
"string" = { fg = "{{ green }}" }
"string.regexp" = { fg = "{{ orange }}" }
"keyword" = { fg = "{{ magenta }}" }
"keyword.control" = { fg = "{{ magenta }}" }
"function" = { fg = "{{ blue }}" }
"function.method" = { fg = "{{ blue }}" }
"type" = { fg = "{{ yellow }}" }
"variable" = { fg = "{{ foreground }}" }
"variable.other.member" = { fg = "{{ cyan }}" }
"variable.parameter" = { fg = "{{ foreground }}" }
"operator" = { fg = "{{ cyan }}" }
"special" = { fg = "{{ orange }}" }

"diagnostic.error" = { underline = { color = "{{ red }}", style = "curl" } }
"diagnostic.warning" = { underline = { color = "{{ yellow }}", style = "curl" } }
"diagnostic.info" = { underline = { color = "{{ blue }}", style = "curl" } }
"diagnostic.hint" = { underline = { color = "{{ green }}", style = "curl" } }

"error" = "{{ red }}"
"warning" = "{{ yellow }}"
"info" = "{{ blue }}"
"hint" = "{{ green }}"
