# ZOI palette for Limine (RRGGBB, no #). Regenerated by zoi-theme.
interface_branding: ZOI
interface_branding_colour: {{ accent_strip }}
interface_help_colour: {{ muted_strip }}
interface_help_colour_bright: {{ accent_strip }}
term_background: ff{{ background_strip }}
term_foreground: {{ foreground_strip }}
term_background_bright: {{ lighter_background_strip }}
term_foreground_bright: {{ bright_foreground_strip }}
term_palette: {{ darker_background_strip }};{{ red_strip }};{{ green_strip }};{{ yellow_strip }};{{ blue_strip }};{{ magenta_strip }};{{ cyan_strip }};{{ foreground_strip }}
term_palette_bright: {{ muted_strip }};{{ bright_red_strip }};{{ bright_green_strip }};{{ bright_yellow_strip }};{{ bright_blue_strip }};{{ bright_magenta_strip }};{{ bright_cyan_strip }};{{ bright_foreground_strip }}
