# Generated by ZOI Theme Manager
client.focused {{ accent }} {{ accent }} {{ dark_background }} {{ orange }} {{ accent }}
client.focused_inactive {{ lighter_background }} {{ lighter_background }} {{ foreground }} {{ lighter_background }} {{ lighter_background }}
client.unfocused {{ dark_background }} {{ dark_background }} {{ muted }} {{ dark_background }} {{ dark_background }}
client.urgent {{ red }} {{ red }} {{ dark_background }} {{ red }} {{ red }}
client.placeholder {{ darker_background }} {{ darker_background }} {{ muted }} {{ darker_background }} {{ darker_background }}
