{
  "workbench.colorCustomizations": {
    "editor.background": "{{ background }}",
    "editor.foreground": "{{ foreground }}",
    "activityBar.background": "{{ darker_background }}",
    "activityBar.foreground": "{{ accent }}",
    "sideBar.background": "{{ dark_background }}",
    "sideBar.foreground": "{{ foreground }}",
    "sideBarTitle.foreground": "{{ accent }}",
    "sideBarSectionHeader.background": "{{ lighter_background }}",
    "statusBar.background": "{{ darker_background }}",
    "statusBar.foreground": "{{ foreground }}",
    "titleBar.activeBackground": "{{ darker_background }}",
    "titleBar.activeForeground": "{{ foreground }}",
    "tab.activeBackground": "{{ background }}",
    "tab.activeForeground": "{{ accent }}",
    "tab.inactiveBackground": "{{ darker_background }}",
    "tab.inactiveForeground": "{{ muted }}",
    "editorGroupHeader.tabsBackground": "{{ darker_background }}",
    "terminal.background": "{{ background }}",
    "terminal.foreground": "{{ foreground }}",
    "terminal.ansiBlack": "{{ dark_background }}",
    "terminal.ansiRed": "{{ red }}",
    "terminal.ansiGreen": "{{ green }}",
    "terminal.ansiYellow": "{{ yellow }}",
    "terminal.ansiBlue": "{{ blue }}",
    "terminal.ansiMagenta": "{{ magenta }}",
    "terminal.ansiCyan": "{{ cyan }}",
    "terminal.ansiWhite": "{{ foreground }}",
    "focusBorder": "{{ accent }}",
    "input.background": "{{ lighter_background }}",
    "input.foreground": "{{ foreground }}",
    "input.border": "{{ muted }}",
    "list.activeSelectionBackground": "{{ selection }}",
    "list.activeSelectionForeground": "{{ accent }}",
    "list.hoverBackground": "{{ lighter_background }}",
    "badge.background": "{{ accent }}",
    "badge.foreground": "{{ dark_background }}"
  }
}
