/* Generated by ZOI Theme Manager — Waybar */
* {
    font-family: DejaVu Sans, sans-serif;
    font-size: 12px;
    min-height: 0;
}

window#waybar {
    background: {{ background }};
    color: {{ foreground }};
    border-bottom: 2px solid {{ accent }};
}

#workspaces button {
    padding: 0 8px;
    color: {{ muted }};
    background: transparent;
    border: none;
    border-radius: 0;
}

#workspaces button.focused,
#workspaces button.active {
    color: {{ dark_background }};
    background: {{ accent }};
}

#workspaces button.urgent {
    color: {{ dark_background }};
    background: {{ red }};
}

#clock,
#custom-weather,
#custom-launcher,
#pulseaudio,
#network,
#battery,
#window,
#tray {
    padding: 0 10px;
    color: {{ foreground }};
}

#custom-launcher {
    font-weight: 700;
    color: {{ dark_background }};
    background: {{ accent }};
    padding: 0 12px;
}

#battery.warning {
    color: {{ yellow }};
}

#battery.critical {
    color: {{ red }};
}

#pulseaudio.muted,
#network.disconnected {
    color: {{ muted }};
}
