# Generated by zoi-theme. Yazi style tables.

[app]
overall = { bg = "{{ background }}" }

[mgr]
cwd = { fg = "{{ cyan }}" }
hovered = { fg = "{{ foreground }}", bg = "{{ selection }}" }
preview_hovered = { underline = true }
find_keyword = { fg = "{{ yellow }}", bold = true }
find_position = { fg = "{{ muted }}" }
marker_copied = { fg = "{{ green }}", bg = "{{ green }}" }
marker_cut = { fg = "{{ red }}", bg = "{{ red }}" }
marker_marked = { fg = "{{ accent }}", bg = "{{ accent }}" }
marker_selected = { fg = "{{ accent }}", bg = "{{ accent }}" }
count_copied = { fg = "{{ background }}", bg = "{{ green }}" }
count_cut = { fg = "{{ background }}", bg = "{{ red }}" }
count_selected = { fg = "{{ background }}", bg = "{{ accent }}" }
border_symbol = "│"
border_style = { fg = "{{ muted }}" }

[tabs]
active = { fg = "{{ background }}", bg = "{{ accent }}", bold = true }
inactive = { fg = "{{ foreground }}", bg = "{{ lighter_background }}" }
sep_inner = { open = "", close = "" }
sep_outer = { open = "", close = "" }

[mode]
normal_main = { fg = "{{ background }}", bg = "{{ accent }}", bold = true }
normal_alt = { fg = "{{ accent }}", bg = "{{ selection }}" }
select_main = { fg = "{{ background }}", bg = "{{ green }}", bold = true }
select_alt = { fg = "{{ green }}", bg = "{{ selection }}" }
unset_main = { fg = "{{ background }}", bg = "{{ red }}", bold = true }
unset_alt = { fg = "{{ red }}", bg = "{{ selection }}" }

[status]
sep_left = { open = "", close = "" }
sep_right = { open = "", close = "" }
overall = { fg = "{{ foreground }}", bg = "{{ dark_background }}" }
perm_type = { fg = "{{ green }}" }
perm_read = { fg = "{{ yellow }}" }
perm_write = { fg = "{{ red }}" }
perm_exec = { fg = "{{ cyan }}" }
perm_sep = { fg = "{{ muted }}" }
progress_label = { bold = true }
progress_normal = { fg = "{{ accent }}", bg = "{{ darker_background }}" }
progress_error = { fg = "{{ red }}", bg = "{{ darker_background }}" }

[input]
border = { fg = "{{ accent }}" }
title = { fg = "{{ accent }}" }
value = { fg = "{{ foreground }}" }
selected = { reversed = true }

[pick]
border = { fg = "{{ accent }}" }
active = { fg = "{{ magenta }}", bold = true }
inactive = { fg = "{{ foreground }}" }

[confirm]
border = { fg = "{{ accent }}" }
title = { fg = "{{ accent }}" }
content = {}
list = {}
btn_yes = { reversed = true }
btn_no = {}

[completion]
border = { fg = "{{ accent }}" }
active = { reversed = true }
inactive = {}

[which]
mask = { bg = "{{ dark_background }}" }
cand = { fg = "{{ cyan }}" }
rest = { fg = "{{ muted }}" }
desc = { fg = "{{ foreground }}" }
separator = "  "
separator_style = { fg = "{{ muted }}" }

[help]
on = { fg = "{{ cyan }}" }
run = { fg = "{{ magenta }}" }
desc = { fg = "{{ foreground }}" }
hovered = { reversed = true, bold = true }
footer = { fg = "{{ background }}", bg = "{{ foreground }}" }

[notify]
title_info = { fg = "{{ green }}" }
title_warn = { fg = "{{ yellow }}" }
title_error = { fg = "{{ red }}" }
icon_info = "i"
icon_warn = "!"
icon_error = "x"

[tasks]
border = { fg = "{{ accent }}" }
title = { fg = "{{ accent }}" }
hovered = { fg = "{{ magenta }}", underline = true }

[indicator]
padding = { open = "", close = "" }


[cmp]
icon_file = "-"
icon_folder = ">"
icon_command = "$"

# No Nerd Fonts in ZOI; use ASCII so DejaVu in foot can render them.
[icon]
globs = []
dirs = []
files = []
exts = []
conds = [
	{ if = "dir", text = ">" },
	{ if = "exec", text = "*" },
	{ if = "link", text = "@" },
	{ if = "orphan", text = "!" },
	{ if = "dummy", text = "?" },
]
